// Code generated by MockGen. DO NOT EDIT.
// Source: events.go

// Package mock_events is a generated GoMock package.
package mock_events

import (
	context "context"
	config "github.com/akhmed9505/event-booker/internal/config"
	domain "github.com/akhmed9505/event-booker/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventService) Create(ctx context.Context, event *domain.Event) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEventServiceMockRecorder) Create(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventService)(nil).Create), ctx, event)
}

// Get mocks base method.
func (m *MockEventService) Get(ctx context.Context, id uuid.UUID) (*domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEventServiceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEventService)(nil).Get), ctx, id)
}

// GetEmailByUserID mocks base method.
func (m *MockEventService) GetEmailByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByUserID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByUserID indicates an expected call of GetEmailByUserID.
func (mr *MockEventServiceMockRecorder) GetEmailByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByUserID", reflect.TypeOf((*MockEventService)(nil).GetEmailByUserID), ctx, userID)
}

// GetUserNameByID mocks base method.
func (m *MockEventService) GetUserNameByID(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserNameByID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserNameByID indicates an expected call of GetUserNameByID.
func (mr *MockEventServiceMockRecorder) GetUserNameByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserNameByID", reflect.TypeOf((*MockEventService)(nil).GetUserNameByID), ctx, userID)
}

// ListEvents mocks base method.
func (m *MockEventService) ListEvents(ctx context.Context) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockEventServiceMockRecorder) ListEvents(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockEventService)(nil).ListEvents), ctx)
}

// UpdateUserEmail mocks base method.
func (m *MockEventService) UpdateUserEmail(ctx context.Context, userID uuid.UUID, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", ctx, userID, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockEventServiceMockRecorder) UpdateUserEmail(ctx, userID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockEventService)(nil).UpdateUserEmail), ctx, userID, email)
}

// MockBookingService is a mock of BookingService interface.
type MockBookingService struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceMockRecorder
}

// MockBookingServiceMockRecorder is the mock recorder for MockBookingService.
type MockBookingServiceMockRecorder struct {
	mock *MockBookingService
}

// NewMockBookingService creates a new mock instance.
func NewMockBookingService(ctrl *gomock.Controller) *MockBookingService {
	mock := &MockBookingService{ctrl: ctrl}
	mock.recorder = &MockBookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingService) EXPECT() *MockBookingServiceMockRecorder {
	return m.recorder
}

// BookSeat mocks base method.
func (m *MockBookingService) BookSeat(ctx context.Context, eventID, userID uuid.UUID, seatID *int) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookSeat", ctx, eventID, userID, seatID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookSeat indicates an expected call of BookSeat.
func (mr *MockBookingServiceMockRecorder) BookSeat(ctx, eventID, userID, seatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookSeat", reflect.TypeOf((*MockBookingService)(nil).BookSeat), ctx, eventID, userID, seatID)
}

// Cancel mocks base method.
func (m *MockBookingService) Cancel(ctx context.Context, bookingID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, bookingID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockBookingServiceMockRecorder) Cancel(ctx, bookingID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockBookingService)(nil).Cancel), ctx, bookingID, userID)
}

// Confirm mocks base method.
func (m *MockBookingService) Confirm(ctx context.Context, bookingID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, bookingID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Confirm indicates an expected call of Confirm.
func (mr *MockBookingServiceMockRecorder) Confirm(ctx, bookingID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockBookingService)(nil).Confirm), ctx, bookingID, userID)
}

// CountBookedSeats mocks base method.
func (m *MockBookingService) CountBookedSeats(ctx context.Context, eventID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBookedSeats", ctx, eventID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBookedSeats indicates an expected call of CountBookedSeats.
func (mr *MockBookingServiceMockRecorder) CountBookedSeats(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBookedSeats", reflect.TypeOf((*MockBookingService)(nil).CountBookedSeats), ctx, eventID)
}

// GetContactByBookingID mocks base method.
func (m *MockBookingService) GetContactByBookingID(ctx context.Context, bookingID uuid.UUID) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByBookingID", ctx, bookingID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetContactByBookingID indicates an expected call of GetContactByBookingID.
func (mr *MockBookingServiceMockRecorder) GetContactByBookingID(ctx, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByBookingID", reflect.TypeOf((*MockBookingService)(nil).GetContactByBookingID), ctx, bookingID)
}

// InsertBookingCancelledEvent mocks base method.
func (m *MockBookingService) InsertBookingCancelledEvent(ctx context.Context, event *domain.BookingCancelledEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBookingCancelledEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBookingCancelledEvent indicates an expected call of InsertBookingCancelledEvent.
func (mr *MockBookingServiceMockRecorder) InsertBookingCancelledEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBookingCancelledEvent", reflect.TypeOf((*MockBookingService)(nil).InsertBookingCancelledEvent), ctx, event)
}

// ListBookings mocks base method.
func (m *MockBookingService) ListBookings(ctx context.Context, eventID uuid.UUID) ([]domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookings", ctx, eventID)
	ret0, _ := ret[0].([]domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookings indicates an expected call of ListBookings.
func (mr *MockBookingServiceMockRecorder) ListBookings(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookings", reflect.TypeOf((*MockBookingService)(nil).ListBookings), ctx, eventID)
}

// StartExpiredBookingCleanerCron mocks base method.
func (m *MockBookingService) StartExpiredBookingCleanerCron(ctx context.Context, schedule string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartExpiredBookingCleanerCron", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartExpiredBookingCleanerCron indicates an expected call of StartExpiredBookingCleanerCron.
func (mr *MockBookingServiceMockRecorder) StartExpiredBookingCleanerCron(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartExpiredBookingCleanerCron", reflect.TypeOf((*MockBookingService)(nil).StartExpiredBookingCleanerCron), ctx, schedule)
}

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyUserBookingCanceled mocks base method.
func (m *MockNotifier) NotifyUserBookingCanceled(ctx context.Context, cfg *config.Config, userEmail, userTelegramID string, bookingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyUserBookingCanceled", ctx, cfg, userEmail, userTelegramID, bookingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyUserBookingCanceled indicates an expected call of NotifyUserBookingCanceled.
func (mr *MockNotifierMockRecorder) NotifyUserBookingCanceled(ctx, cfg, userEmail, userTelegramID, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyUserBookingCanceled", reflect.TypeOf((*MockNotifier)(nil).NotifyUserBookingCanceled), ctx, cfg, userEmail, userTelegramID, bookingID)
}
