// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package mock_eventbroker is a generated GoMock package.
package mock_eventbroker

import (
	context "context"
	reflect "reflect"

	config "github.com/akhmed9505/event-booker/internal/config"
	domain "github.com/akhmed9505/event-booker/internal/domain"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockEventHandler is a mock of EventHandler interface.
type MockEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventHandlerMockRecorder
}

// MockEventHandlerMockRecorder is the mock recorder for MockEventHandler.
type MockEventHandlerMockRecorder struct {
	mock *MockEventHandler
}

// NewMockEventHandler creates a new mock instance.
func NewMockEventHandler(ctrl *gomock.Controller) *MockEventHandler {
	mock := &MockEventHandler{ctrl: ctrl}
	mock.recorder = &MockEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventHandler) EXPECT() *MockEventHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventHandler) Create(ctx context.Context, event *domain.Event) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEventHandlerMockRecorder) Create(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventHandler)(nil).Create), ctx, event)
}

// Get mocks base method.
func (m *MockEventHandler) Get(ctx context.Context, id uuid.UUID) (*domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEventHandlerMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEventHandler)(nil).Get), ctx, id)
}

// GetEmailByUserID mocks base method.
func (m *MockEventHandler) GetEmailByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByUserID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByUserID indicates an expected call of GetEmailByUserID.
func (mr *MockEventHandlerMockRecorder) GetEmailByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByUserID", reflect.TypeOf((*MockEventHandler)(nil).GetEmailByUserID), ctx, userID)
}

// GetUserNameByID mocks base method.
func (m *MockEventHandler) GetUserNameByID(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserNameByID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserNameByID indicates an expected call of GetUserNameByID.
func (mr *MockEventHandlerMockRecorder) GetUserNameByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserNameByID", reflect.TypeOf((*MockEventHandler)(nil).GetUserNameByID), ctx, userID)
}

// ListEvents mocks base method.
func (m *MockEventHandler) ListEvents(ctx context.Context) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockEventHandlerMockRecorder) ListEvents(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockEventHandler)(nil).ListEvents), ctx)
}

// UpdateUserEmail mocks base method.
func (m *MockEventHandler) UpdateUserEmail(ctx context.Context, userID uuid.UUID, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", ctx, userID, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockEventHandlerMockRecorder) UpdateUserEmail(ctx, userID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockEventHandler)(nil).UpdateUserEmail), ctx, userID, email)
}

// MockBookingHandler is a mock of BookingHandler interface.
type MockBookingHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBookingHandlerMockRecorder
}

// MockBookingHandlerMockRecorder is the mock recorder for MockBookingHandler.
type MockBookingHandlerMockRecorder struct {
	mock *MockBookingHandler
}

// NewMockBookingHandler creates a new mock instance.
func NewMockBookingHandler(ctrl *gomock.Controller) *MockBookingHandler {
	mock := &MockBookingHandler{ctrl: ctrl}
	mock.recorder = &MockBookingHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingHandler) EXPECT() *MockBookingHandlerMockRecorder {
	return m.recorder
}

// BookSeat mocks base method.
func (m *MockBookingHandler) BookSeat(ctx context.Context, eventID, userID uuid.UUID, seatID *int) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookSeat", ctx, eventID, userID, seatID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookSeat indicates an expected call of BookSeat.
func (mr *MockBookingHandlerMockRecorder) BookSeat(ctx, eventID, userID, seatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookSeat", reflect.TypeOf((*MockBookingHandler)(nil).BookSeat), ctx, eventID, userID, seatID)
}

// Cancel mocks base method.
func (m *MockBookingHandler) Cancel(ctx context.Context, bookingID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, bookingID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockBookingHandlerMockRecorder) Cancel(ctx, bookingID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockBookingHandler)(nil).Cancel), ctx, bookingID, userID)
}

// Confirm mocks base method.
func (m *MockBookingHandler) Confirm(ctx context.Context, bookingID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, bookingID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Confirm indicates an expected call of Confirm.
func (mr *MockBookingHandlerMockRecorder) Confirm(ctx, bookingID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockBookingHandler)(nil).Confirm), ctx, bookingID, userID)
}

// CountBookedSeats mocks base method.
func (m *MockBookingHandler) CountBookedSeats(ctx context.Context, eventID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBookedSeats", ctx, eventID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBookedSeats indicates an expected call of CountBookedSeats.
func (mr *MockBookingHandlerMockRecorder) CountBookedSeats(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBookedSeats", reflect.TypeOf((*MockBookingHandler)(nil).CountBookedSeats), ctx, eventID)
}

// GetContactByBookingID mocks base method.
func (m *MockBookingHandler) GetContactByBookingID(ctx context.Context, bookingID uuid.UUID) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByBookingID", ctx, bookingID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetContactByBookingID indicates an expected call of GetContactByBookingID.
func (mr *MockBookingHandlerMockRecorder) GetContactByBookingID(ctx, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByBookingID", reflect.TypeOf((*MockBookingHandler)(nil).GetContactByBookingID), ctx, bookingID)
}

// InsertBookingCancelledEvent mocks base method.
func (m *MockBookingHandler) InsertBookingCancelledEvent(ctx context.Context, event *domain.BookingCancelledEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBookingCancelledEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBookingCancelledEvent indicates an expected call of InsertBookingCancelledEvent.
func (mr *MockBookingHandlerMockRecorder) InsertBookingCancelledEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBookingCancelledEvent", reflect.TypeOf((*MockBookingHandler)(nil).InsertBookingCancelledEvent), ctx, event)
}

// ListBookings mocks base method.
func (m *MockBookingHandler) ListBookings(ctx context.Context, eventID uuid.UUID) ([]domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookings", ctx, eventID)
	ret0, _ := ret[0].([]domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookings indicates an expected call of ListBookings.
func (mr *MockBookingHandlerMockRecorder) ListBookings(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookings", reflect.TypeOf((*MockBookingHandler)(nil).ListBookings), ctx, eventID)
}

// MockNotification is a mock of Notification interface.
type MockNotification struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationMockRecorder
}

// MockNotificationMockRecorder is the mock recorder for MockNotification.
type MockNotificationMockRecorder struct {
	mock *MockNotification
}

// NewMockNotification creates a new mock instance.
func NewMockNotification(ctrl *gomock.Controller) *MockNotification {
	mock := &MockNotification{ctrl: ctrl}
	mock.recorder = &MockNotificationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotification) EXPECT() *MockNotificationMockRecorder {
	return m.recorder
}

// NotifyUserBookingCanceled mocks base method.
func (m *MockNotification) NotifyUserBookingCanceled(ctx context.Context, cfg *config.Config, userEmail, userTelegramID string, bookingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyUserBookingCanceled", ctx, cfg, userEmail, userTelegramID, bookingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyUserBookingCanceled indicates an expected call of NotifyUserBookingCanceled.
func (mr *MockNotificationMockRecorder) NotifyUserBookingCanceled(ctx, cfg, userEmail, userTelegramID, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyUserBookingCanceled", reflect.TypeOf((*MockNotification)(nil).NotifyUserBookingCanceled), ctx, cfg, userEmail, userTelegramID, bookingID)
}
